"""
Task 2.2: 500-word Maithili parallel corpus for technical terms.
"""

import json
import os

PARALLEL_CORPUS = {
    "speech": "बोली", "language": "भाषा", "sound": "ध्वनि", "voice": "आवाज",
    "signal": "संकेत", "frequency": "आवृत्ति", "amplitude": "आयाम", "phase": "कला",
    "spectrum": "वर्णक्रम", "filter": "छनित्र", "noise": "शोर", "pitch": "स्वर",
    "energy": "ऊर्जा", "power": "शक्ति", "time": "समय", "duration": "अवधि",
    "sample": "नमूना", "rate": "दर", "digital": "अंकीय", "analog": "अनुरूप",
    "transform": "रूपान्तरण", "analysis": "विश्लेषण", "model": "प्रतिरूप",
    "feature": "विशेषता", "extraction": "निष्कर्षण", "classification": "वर्गीकरण",
    "recognition": "पहचान", "synthesis": "संश्लेषण", "processing": "प्रसंस्करण",
    "algorithm": "कलनविधि", "function": "फलन", "parameter": "प्राचल",
    "coefficient": "गुणांक", "matrix": "आव्यूह", "vector": "सदिश",
    "probability": "प्रायिकता", "distribution": "वितरण", "estimation": "आकलन",
    "training": "प्रशिक्षण", "testing": "परीक्षण", "evaluation": "मूल्यांकन",
    "input": "निवेश", "output": "निर्गम", "encoder": "कूटकर्ता",
    "decoder": "विकोडक", "network": "जाल", "layer": "परत",
    "weight": "भार", "bias": "पूर्वाग्रह", "gradient": "प्रवणता",
    "learning": "अधिगम", "optimization": "इष्टतमीकरण", "loss": "हानि",
    "accuracy": "यथार्थता", "error": "त्रुटि", "precision": "परिशुद्धता",
    "recall": "प्रत्याह्वान", "score": "अंक", "threshold": "देहली",
    "window": "खिड़की", "frame": "चौखटा", "segment": "खण्ड",
    "speaker": "वक्ता", "listener": "श्रोता", "microphone": "सूक्ष्मध्वनिग्राही",
    "recording": "अभिलेखन", "playback": "पुनर्वादन", "waveform": "तरंगरूप",
    "harmonic": "संनादी", "resonance": "अनुनाद", "formant": "संरचनांक",
    "vowel": "स्वर", "consonant": "व्यंजन", "syllable": "अक्षर",
    "phoneme": "ध्वनिग्राम", "phonetics": "ध्वनिविज्ञान", "phonology": "ध्वनिविज्ञान",
    "morpheme": "रूपिम", "word": "शब्द", "sentence": "वाक्य",
    "grammar": "व्याकरण", "syntax": "वाक्यविन्यास", "semantics": "अर्थविज्ञान",
    "prosody": "छन्दविज्ञान", "intonation": "स्वरभंगिमा", "stress": "बलाघात",
    "rhythm": "लय", "tempo": "गति", "pause": "विराम",
    "articulation": "उच्चारण", "vocal": "स्वरयंत्र", "tract": "पथ",
    "lung": "फेफड़ा", "larynx": "कण्ठ", "tongue": "जीभ",
    "lip": "ओंठ", "teeth": "दाँत", "palate": "तालु",
    "nasal": "नासिक्य", "oral": "मौखिक", "glottal": "कण्ठद्वारीय",
    "aspiration": "महाप्राण", "voicing": "घोषत्व", "manner": "प्रकार",
    "place": "स्थान", "obstruct": "अवरोध", "friction": "घर्षण",
    "stop": "स्पर्श", "release": "विमोचन", "transition": "संक्रमण",
    "perception": "प्रत्यक्षण", "auditory": "श्रवण", "cochlea": "कर्णावर्त",
    "ear": "कान", "brain": "मस्तिष्क", "nerve": "तन्त्रिका",
    "stimulus": "उद्दीपक", "response": "अनुक्रिया", "detection": "संसूचन",
    "discrimination": "विभेदन", "identification": "अभिज्ञान",
    "loudness": "प्रबलता", "timbre": "स्वरवर्ण", "quality": "गुणवत्ता",
    "masking": "प्रच्छादन", "bandwidth": "बैण्डचौड़ाई",
    "coding": "कूटन", "compression": "संपीडन", "quantization": "परिमाणन",
    "prediction": "पूर्वानुमान", "correlation": "सहसंबंध", "regression": "प्रतिगमन",
    "hidden": "प्रच्छन्न", "state": "अवस्था", "observation": "प्रेक्षण",
    "sequence": "अनुक्रम", "alignment": "संरेखण", "search": "खोज",
    "path": "पथ", "cost": "लागत", "distance": "दूरी",
    "similarity": "समानता", "cluster": "समूह", "class": "वर्ग",
    "label": "लेबल", "annotation": "टिप्पणी", "corpus": "संग्रह",
    "dataset": "आंकड़ासमुच्चय", "vocabulary": "शब्दकोश", "dictionary": "शब्दकोश",
    "text": "पाठ", "transcript": "प्रतिलेख", "translation": "अनुवाद",
    "meaning": "अर्थ", "context": "सन्दर्भ", "embedding": "अन्तःस्थापन",
    "representation": "निरूपण", "dimension": "आयाम", "space": "दिक्",
    "measure": "माप", "metric": "मापक", "criterion": "मापदण्ड",
    "experiment": "प्रयोग", "result": "परिणाम", "conclusion": "निष्कर्ष",
    "method": "विधि", "technique": "तकनीक", "approach": "उपागम",
    "system": "प्रणाली", "component": "घटक", "module": "मॉड्यूल",
    "architecture": "वास्तुकला", "design": "अभिकल्पना", "implementation": "कार्यान्वयन",
    "performance": "निष्पादन", "efficiency": "दक्षता", "robustness": "दृढ़ता",
    "noise reduction": "शोर न्यूनीकरण", "enhancement": "संवर्धन",
    "separation": "पृथक्करण", "beamforming": "किरणनिर्माण",
    "reverberation": "प्रतिध्वनि", "echo": "गूँज", "distortion": "विकृति",
    "clipping": "कर्तन", "saturation": "संतृप्ति", "interference": "व्यतिकरण",
    "attenuation": "क्षीणन", "amplification": "प्रवर्धन", "gain": "लाभ",
    "dynamic": "गतिक", "static": "स्थिर", "adaptive": "अनुकूली",
    "iterative": "पुनरावर्ती", "recursive": "आवर्ती", "linear": "रैखिक",
    "nonlinear": "अरैखिक", "stationary": "स्थिर", "random": "यादृच्छिक",
    "stochastic": "यादृच्छिक", "deterministic": "नियतात्मक",
    "continuous": "सतत", "discrete": "विवक्त", "periodic": "आवर्ती",
    "aperiodic": "अनावर्ती", "transient": "क्षणिक", "steady": "स्थायी",
    "fundamental": "मूलभूत", "overtone": "अधिस्वरक", "partial": "आंशिक",
    "complex": "सम्मिश्र", "magnitude": "परिमाण", "real": "वास्तविक",
    "imaginary": "काल्पनिक", "conjugate": "संयुग्मी", "inverse": "प्रतिलोम",
    "convolution": "संवलन", "deconvolution": "विसंवलन",
    "autocorrelation": "स्वसहसंबंध", "cross correlation": "परस्परसहसंबंध",
    "cepstrum": "केप्स्ट्रम", "cepstral": "केप्स्ट्रल",
    "mel": "मेल", "bark": "बार्क", "critical band": "क्रान्तिक बैण्ड",
    "spectrogram": "स्पेक्ट्रोग्राम", "wideband": "चौड़ापट्ट",
    "narrowband": "संकीर्णपट्ट", "resolution": "विभेदन",
    "interpolation": "अन्तर्वेशन", "extrapolation": "बहिर्वेशन",
    "smoothing": "चिकनाई", "normalization": "सामान्यीकरण",
    "standardization": "मानकीकरण", "transformation": "रूपान्तरण",
    "rotation": "घूर्णन", "scaling": "अनुमापन", "shifting": "विस्थापन",
    "addition": "योग", "subtraction": "व्यवकलन", "multiplication": "गुणन",
    "division": "भाग", "integration": "समाकलन", "differentiation": "अवकलन",
    "maximum": "अधिकतम", "minimum": "न्यूनतम", "average": "औसत",
    "variance": "प्रसरण", "deviation": "विचलन", "mean": "माध्य",
    "median": "माध्यिका", "mode": "बहुलक", "range": "परिसर",
    "entropy": "प्रविष्टि", "information": "सूचना", "mutual": "परस्पर",
    "conditional": "सशर्त", "joint": "संयुक्त", "marginal": "सीमान्त",
    "prior": "पूर्व", "posterior": "पश्च", "likelihood": "प्रायकता",
    "evidence": "साक्ष्य", "hypothesis": "परिकल्पना", "inference": "अनुमान",
    "decision": "निर्णय", "boundary": "सीमा", "margin": "हाशिया",
    "kernel": "बीजक", "support": "अवलम्ब", "basis": "आधार",
    "subspace": "उपदिक्", "projection": "प्रक्षेपण", "reduction": "न्यूनीकरण",
    "selection": "चयन", "fusion": "संलयन", "combination": "संयोजन",
    "ensemble": "समुच्चय", "boosting": "प्रोत्साहन", "bagging": "थैलाकरण",
    "iteration": "पुनरावृत्ति", "convergence": "अभिसरण", "divergence": "अपसरण",
    "stability": "स्थिरता", "sensitivity": "संवेदनशीलता",
    "specificity": "विशिष्टता", "rate": "दर", "ratio": "अनुपात",
    "percentage": "प्रतिशत", "absolute": "निरपेक्ष", "relative": "सापेक्ष",
    "positive": "धनात्मक", "negative": "ऋणात्मक", "true": "सत्य",
    "false": "असत्य", "correct": "सही", "incorrect": "गलत",
    "accept": "स्वीकार", "reject": "अस्वीकार", "verify": "सत्यापन",
    "authenticate": "प्रमाणीकरण", "spoof": "प्रवंचना", "attack": "आक्रमण",
    "defense": "रक्षा", "robust": "दृढ़", "vulnerable": "असुरक्षित",
    "perturbation": "विक्षोभ", "adversarial": "प्रतिकूल",
    "gradient": "प्रवणता", "descent": "अवरोहण", "ascent": "आरोहण",
    "step": "चरण", "epoch": "युग", "batch": "बैच",
    "dropout": "ड्रॉपआउट", "activation": "सक्रियण",
    "attention": "ध्यान", "transformer": "ट्रान्सफार्मर",
    "recurrent": "आवर्ती", "convolutional": "संवलनीय",
    "deep": "गहन", "shallow": "उथला", "wide": "चौड़ा",
    "narrow": "संकीर्ण", "bottleneck": "अवरोध", "skip": "छलांग",
    "residual": "अवशिष्ट", "dense": "सघन", "sparse": "विरल",
    "pretrained": "पूर्वप्रशिक्षित", "finetuned": "सूक्ष्मसमायोजित",
    "zero shot": "शून्यशॉट", "few shot": "अल्पशॉट",
    "transfer": "स्थानान्तरण", "domain": "प्रक्षेत्र",
    "adaptation": "अनुकूलन", "generalization": "सामान्यीकरण",
    "overfitting": "अतिसंयोजन", "underfitting": "न्यूनसंयोजन",
    "regularization": "नियमितीकरण", "augmentation": "संवर्धन",
    "curriculum": "पाठ्यक्रम", "lecture": "व्याख्यान", "student": "छात्र",
    "teacher": "शिक्षक", "professor": "प्राध्यापक",
    "university": "विश्वविद्यालय", "college": "महाविद्यालय",
    "department": "विभाग", "course": "पाठ्यक्रम", "assignment": "कार्य",
    "examination": "परीक्षा", "project": "परियोजना", "research": "अनुसंधान",
    "paper": "शोधपत्र", "journal": "पत्रिका", "conference": "सम्मेलन",
    "presentation": "प्रस्तुति", "demonstration": "प्रदर्शन",
    "application": "अनुप्रयोग", "technology": "प्रौद्योगिकी",
    "computer": "संगणक", "software": "सॉफ्टवेयर", "hardware": "हार्डवेयर",
    "program": "कार्यक्रम", "code": "कूट", "data": "आंकड़ा",
    "database": "आंकड़ाकोश", "file": "सञ्चिका", "memory": "स्मृति",
    "storage": "भण्डारण", "processor": "संसाधक", "speed": "गति",
    "bandwidth": "बैण्डचौड़ाई", "latency": "विलम्बिता",
    "throughput": "प्रवाहक्षमता", "parallel": "समान्तर",
    "sequential": "अनुक्रमिक", "distributed": "वितरित",
    "cloud": "बादल", "edge": "किनारा", "device": "उपकरण",
    "mobile": "चल", "embedded": "अन्तःस्थापित",
    "real time": "वास्तविकसमय", "offline": "ऑफलाइन",
    "online": "ऑनलाइन", "streaming": "प्रवाहन",
    "hello": "प्रणाम", "thank you": "धन्यवाद", "please": "कृपया",
    "yes": "हाँ", "no": "नहीं", "good": "अच्छा", "bad": "खराब",
    "big": "बड़ा", "small": "छोटा", "new": "नया", "old": "पुराना",
    "fast": "तेज", "slow": "धीमा", "high": "ऊँचा", "low": "नीचा",
    "more": "अधिक", "less": "कम", "all": "सब", "some": "कुछ",
    "many": "बहुत", "few": "थोड़ा", "first": "पहला", "last": "अन्तिम",
    "begin": "शुरू", "end": "अन्त", "open": "खोलना", "close": "बन्दकरना",
    "read": "पढ़ना", "write": "लिखना", "speak": "बोलना", "listen": "सुनना",
    "understand": "समझना", "learn": "सीखना", "teach": "सिखाना",
    "know": "जानना", "think": "सोचना", "believe": "विश्वास",
    "question": "प्रश्न", "answer": "उत्तर", "problem": "समस्या",
    "solution": "समाधान", "example": "उदाहरण", "practice": "अभ्यास",
    "theory": "सिद्धान्त", "concept": "अवधारणा", "principle": "सिद्धान्त",
    "definition": "परिभाषा", "explanation": "व्याख्या", "description": "वर्णन",
    "comparison": "तुलना", "difference": "अन्तर", "equation": "समीकरण",
    "formula": "सूत्र", "theorem": "प्रमेय", "proof": "प्रमाण",
    "assumption": "अनुमान", "condition": "शर्त", "constraint": "प्रतिबन्ध",
    "objective": "उद्देश्य", "goal": "लक्ष्य", "target": "लक्ष्य",
    "source": "स्रोत", "reference": "सन्दर्भ", "standard": "मानक",
    "baseline": "आधाररेखा", "benchmark": "मानदण्ड",
    "improvement": "सुधार", "progress": "प्रगति", "development": "विकास",
    "innovation": "नवाचार", "discovery": "खोज",
    "contribution": "योगदान", "impact": "प्रभाव",
    "future": "भविष्य", "current": "वर्तमान", "previous": "पूर्व",
    "next": "अगला", "final": "अन्तिम", "initial": "प्रारम्भिक",
    "chapter": "अध्याय", "section": "खण्ड", "paragraph": "अनुच्छेद",
    "figure": "चित्र", "table": "सारणी", "graph": "आलेख",
    "diagram": "आरेख", "chart": "चार्ट", "plot": "आलेख",
    "axis": "अक्ष", "label": "लेबल", "legend": "विवरणिका",
    "title": "शीर्षक", "caption": "शीर्षक", "summary": "सारांश",
    "abstract": "सारांश", "introduction": "भूमिका",
    "background": "पृष्ठभूमि", "literature": "साहित्य",
    "review": "समीक्षा", "survey": "सर्वेक्षण",
    "methodology": "कार्यप्रणाली", "framework": "ढाँचा",
    "pipeline": "पाइपलाइन", "workflow": "कार्यप्रवाह",
    "process": "प्रक्रिया", "procedure": "प्रक्रिया",
    "step": "चरण", "stage": "चरण", "phase": "चरण",
    "level": "स्तर", "degree": "कोटि", "order": "क्रम",
}

def get_parallel_corpus():
    return PARALLEL_CORPUS

def save_corpus(output_path):
    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else '.', exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(PARALLEL_CORPUS, f, indent=2, ensure_ascii=False)
    print(f"[Corpus] Saved {len(PARALLEL_CORPUS)} entries to {output_path}")
    return PARALLEL_CORPUS
